version: '2'

services:
  mysql:
    image: mysql:5.7
    networks:
      testnet:
        aliases:
          - mysql.local
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=medicoredb
    volumes:
      - db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - '3306:3306'

volumes:
  db:

networks:
  testnet:
